### ISSUE TITLE
Obsługa opcjonalnej daty w OracleDataReader (nullable)

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-mf-net-core-3#1]
Chciałem podziękować za zeszłotygodniowe szkolenie, bardzo się przydało i wszystkie zmiany udało mi się już wprowadzić, wraz z kompresją odpowiedzi.

 

Pozostał nam jednak jeden - ostatni problem, z tymi null-ami bazodanowymi w OracleDataReader, błąd: System.InvalidCastException: „Column contains NULL data”, jest problem szczególnie ze stringami i datami.

 

Szukałem rozwiązania w sieci, znalazłem m.in. https://docs.oracle.com/database/121/ODPNT/OracleDataReaderClass.htm#ODPNT1192

Zadziałało mi jedno z rozwiązań: !reader.IsDBNull(6) ? reader.GetDateTime(6) : new DateTime(0) ale nie do końca tak jak chciałem, bo data domyślna pusta to: "0001-01-01T00:00:00"

 

Proszę jeszcze o pomoc w tym temacie, jeżeli to możliwe.

**Comment by sulmar** [comment]
Można to zrealizować bardzo elegancko za pomocą metod rozszerzających (Extensions Methods).
 
Przykład:
https://github.com/sulmar/sulmar-mf-net-core-3/blob/master/MF.Rb.OracleDbRepository/DbCustomerRepository.cs

**Comment by sulmar** [comment]
Dodałem kolejne metody rozszerzające do obsługi string i liczb całkowitych (int16, int32, int64).
Dzięki temu możemy odwoływać się w ten sposób:

```
 Name = reader.GetNullableString(3);
 ParentId = reader.GetNullableInt32(5); 

```
Lub bezpieczniej po nazwie kolumny:

```
Name = reader.GetNullableString("Name"); 
ParentId = reader.GetNullableInt32("ParentId"); 

```

Kod:https://github.com/sulmar/sulmar-mf-net-core-3/blob/master/MF.Rb.OracleDbRepository/DbCustomerRepository.cs

Na podobnej zasadzie można dodać obsługę pozostałych typów danych.

**Comment by AdamPiotr** [comment]
Dziękuję, przetestuję w wolnej chwili
